algo = str(input('Digite algo: '))
print('O tipo primitivo é {}'.format(type(algo)))
print('Só tem espaços?{}'.format(algo.isspace()))
print('Tem número?{}'.format(algo.isnumeric()))
print('É alfabético?{}'.format(algo.isalpha()))
print('É alfanumérico?{}'.format(algo.isalnum()))
print('Está em maiúscolo {}'.format(algo.isupper()))
print('Está em minúscolo{}'.format(algo.islower()))
print('Está capitalizada?{}'.format(algo.istitle()))